#! /bin/bash
# clear picture orientation
source Common.sh


# Function to process a single file
process_file() {
    source Common.sh
    local A="$1"
    pre
    # convert_it "$A" -auto-orient -strip -orient Undefined "$A"
    # Orientation                     : Horizontal (normal)
    exiftool -orientation#=1 "$A"
    convert_it "$A" -auto-orient -strip "$A"
}

# Export the function so xargs can use it
export -f process_file

# Process files in parallel using xargs
echo "$FILES" | tr ';' '\n' | xargs -I {} -P $(nproc) bash -c 'process_file "$@"' _ {}

