#! /bin/bash
source Common.sh

# Function to process a single file
process_file() {
    source Common.sh
    local A="$1"
    pre
    # first number (120) controls brightness (100 = normal, >100 = brighter).
    convert_it "$A" -modulate 120,100,100 "$A"
}


# Export the function so xargs can use it
export -f process_file

# Process files in parallel using xargs
echo "$FILES" | tr ';' '\n' | xargs -I {} -P $(nproc) bash -c 'process_file "$@"' _ {}
