#! /bin/bash
source Common.sh
for A in $FILES; do
   pre
   # Note:
   #
   # The `-all=` option in `exiftool` is used to **remove all metadata** from a file. More specifically:
   # - It clears (deletes) **all** Exif, IPTC, XMP, GPS, and other metadata tags that are embedded in the file.
   # - The file itself remains intact, but its metadata will be stripped away.
   exiftool -overwrite_original "-FileModifyDate<CreateDate" "-DateTimeOriginal<CreateDate" "$A"
   # exiftool -all= -overwrite_original "-FileModifyDate<CreateDate" "-DateTimeOriginal<CreateDate" "$A"
   # exiftool -all= "-CreateDate<FileModifyDate" "-DateTimeOriginal<FileModifyDate" "$A"
   # exiftool -overwrite_original -all= "-CreateDate<FileModifyDate" "-DateTimeOriginal<FileModifyDate" -tagsFromFile @ "$A"
   # exiftool -all= -overwrite_original_in_place "-CreateDate<FileModifyDate" "-DateTimeOriginal<FileModifyDate" "$A"
done
