#! /bin/bash

source Common.sh

DATE=$(date +%Y%m%d%H%M%S)

for A in $FILES; do
   pre
   get_trunc_name
   pdftoppm -r 300 -jpeg "$A" "${TRUNCNAME}"
   # convert -density 300 "$A" -quality 100 "$DIR/$FILE_NO_EXT-%03d.jpg"
done
