#! /bin/bash
# intelligently resize to center gravity
source Common.sh

# Function to process a single file
process_file() {
    source Common.sh
    local A="$1"
    pre
    convert_it "$A" -resize 300x100^ -gravity center -extent 300x100 "$A"
    # advent calendar size
    # convert_it "$A" -resize 600x420^ -gravity center -extent 600x420 "$A"
    # convert_it "$A" -resize 1920x1080^ -gravity center -extent 1920x1080 "$A"
}

# Export the function so xargs can use it
export -f process_file

# Process files in parallel using xargs
echo "$FILES" | tr ';' '\n' | xargs -I {} -P $(nproc) bash -c 'process_file "$@"' _ {}

