#! /bin/bash
source Common.sh

# Function to process a single file
process_file() {
    source Common.sh
    local A="$1"
    pre
    NEWFILE="${BASEDIR}/${FILE_NO_EXT}.${EXT}"
    convert_it "$A" -flop $NEWFILE
}

# Export the function so xargs can use it
export -f process_file

# Process files in parallel using xargs
echo "$FILES" | tr ';' '\n' | xargs -I {} -P $(nproc) bash -c 'process_file "$@"' _ {}
