#! /bin/bash
source Common.sh
for A in $FILES; do
   pre
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '3072x>' -resize 'x3072>' "$A"
   # convert_it "$A" -auto-orient -strip -resize 64x100\! "$A"
   convert_it "$A" -auto-orient -strip -resize 600x420\! "$A"
   # convert_it "$A" -auto-orient -resize 50% "$A"
done
