#! /bin/bash
# source Common.sh

filename="montage_001.jpg"
counter=1

# Target size for the images
width=1024

for img in "$@"; do
  convert "$img" -resize "${width}x" "$img"
done

function create_uniq_filename ()
{
   while [[ -e $filename ]]; do
      counter=$((counter + 1))
      filename=$(printf "montage_%03d.jpg" $counter)
   done
}

# create_uniq_filename
# montage -tile 2x4 -mode Concatenate -gravity NorthWest -alpha off -background darkgrey -monitor "$@" -geometry 200x200+5+5 "$filename"
create_uniq_filename
montage -tile 2x4 -mode Concatenate -gravity NorthWest -alpha off -background darkgrey -monitor "$@" "$filename"
