#! /bin/bash
source Common.sh
for A in $FILES; do
   pre
   # book thumbs
   # convert "$A" -auto-orient -strip -quality 50% -resize '64x>' -resize 'x64>' "$A"
   # video thumbs
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '300x>' -resize 'x300>' "$A"
   # standard
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '2048x>' -resize 'x2048>' "$A"
   # higher
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '3072x>' -resize 'x3072>' "$A"
   # other
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '800x>' -resize 'x800>' "$A"
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '640x>' -resize 'x640>' "$A"
   # convert_it "$A" -resize 640x360^ -gravity center -extent 640x360 "$A"
   convert_it "$A" -resize 600x420^ -gravity center -extent 600x420 "$A"
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '1920x>' -resize 'x1920>' "$A"
   # convert_it "$A" -auto-orient -strip -quality 50% -resize '1024x>' -resize 'x1024>' "$A"
done
