#! /bin/bash
source Common.sh

# Function to process a single file
process_file() {
    source Common.sh
    local A="$1"
    pre
    # book thumbs
    # convert_it "$A" -auto-orient -strip -quality 50% -resize 'x64>' "$A"
    # video thumbs
    # convert_it "$A" -auto-orient -strip -quality 50% -resize '360x>' -resize 'x360>' "$A"
    # standard
    # convert_it "$A" -auto-orient -strip -quality 50% -resize '2048x>' -resize 'x2048>' "$A"
    # higher
    # convert_it "$A" -auto-orient -strip -quality 50% -resize '3072x>' -resize 'x3072>' "$A"
    # other
    # convert_it "$A" -auto-orient -strip -quality 50% -resize '800x>' -resize 'x800>' "$A"
    # convert_it "$A" -auto-orient -strip -quality 50% -resize '640x>' -resize 'x640>' "$A"
    # convert_it "$A" -resize 640x360^ -gravity center -extent 640x360 "$A"
    # convert_it "$A" -resize 600x420^ -gravity center -extent 600x420 "$A"
    # convert_it "$A" -auto-orient -strip -quality 50% -resize '1920x>' -resize 'x1920>' "$A"
    # convert_it "$A" -auto-orient -strip -quality 50% -resize '1024x>' -resize 'x1024>' "$A"
    convert_it "$A" -auto-orient -strip -quality 50% -resize '640x>' -resize 'x640>' "$A"
}

# Export the function so xargs can use it
export -f process_file

# Process files in parallel using xargs
echo "$FILES" | tr ';' '\n' | xargs -I {} -P $(nproc) bash -c 'process_file "$@"' _ {}

