#!/bin/bash

# Declare an associative array
declare -A array

# Source external script Common.sh
source Common.sh

# Initialize variables
tagCat=""
IFS=";" read -r tagList files <<< "$FILES"
tags=("$tagList")

# Replace '@' by space, de-duplicate and join with ';' again to get unique keywords.
uniqKeywords=$(echo "${tags//@/ }" | tr ' ' '\n' | sort -u | tr '\n' ';' | xargs)

# Split tagList into hierarchical categories and populate associative array.
for item in "${tags[@]}"; do
    top=${item%@*}
    bot=${item#*@}
    if [[ "$top" != "$bot" ]]; then
        array[$top]+=" $bot"
    else
        array[$top]+=""
    fi
done

# Build XML structure for categories.
tagCat+="<Categories>"
for item in "${!array[@]}"; do
    tagCat+="<Category Assigned=\"1\">$item"
    for index in ${array["$item"]}; do
        tagCat+="<Category Assigned=\"1\">$index</Category>"
    done
    tagCat+="</Category>"
done
tagCat+="</Categories>"

# Now loop over each file in the list and apply tags.
IFS=";"
for A in $files; do
    if [[ -n "$A" ]]; then
        # Modify tags and keywords by replacing specific characters.
        fileTags="${tagList// /,}"
        fileTags="${fileTags//@/\/}"

        if [[ -n "$fileTags" ]]; then
            echo "Processing file: $A"
            echo "Tags: $fileTags"
            echo "Keywords: $uniqKeywords"

            # Run exiftool for hierarchical categories and tags.
            exiftool -overwrite_original_in_place -Categories="$tagCat" "$A"
            exiftool -overwrite_original -sep "," -TagsList="$fileTags" -XMP-microsoft:LastKeywordXMP="$fileTags" "$A"
            fileTags="${fileTags//\//|}"
            exiftool -overwrite_original -sep "," -HierarchicalSubject="$fileTags" -XMP-mediapro:CatalogSets="$fileTags" "$A"
            keyw="${uniqKeywords//;/,}"
            keyw="${keyw%,}"
            exiftool -overwrite_original -sep "," -XPKeywords="$keyw" -Subject="$keyw" -Keywords="$keyw" -LastKeywordIPTC="$keyw" "$A"
        else
            echo "NO TAGS!! $A"
        fi
    fi
done
