#!/bin/bash
declare -A array

source Common.sh

# art art@creatures

# echo "input tags - one@number two one"
# read -e tags

# tags="one@number two one"

# keyw=${tags//@/ } # one number two one
# keyw=$(echo $keyw | sed 's/ /\n/g' | sort | uniq | tr '\n' ';' | xargs) # one number two

# echo "input keyw - one number two"
# read -e keyw

# keyw="one number two"

# echo "tags : $tags : keyw : $keyw"

ftt=0

# for A in $FILES; do
#    echo $A
# done
# exit

for A in $FILES; do
   if [[ $ftt == 0 ]]; then
      echo "ftt"
      gtags=$A
      gkeyw=${gtags//@/ } # one number two one
      gkeyw=$(echo $gkeyw | sed 's/ /\n/g' | sort | uniq | tr '\n' ';' | xargs) # one number two
      ftt=1
   else
      export IFS=" "
      tags=$gtags
      keyw=$gkeyw
      echo "tags : $tags : keyw : $keyw"
      for item in $tags; do
         top=${item%@*}
         bot=${item#*@}
         if [[ "$top" != "$bot" ]]; then
            array[$top]+=" $bot"
         else
            array[$top]+=""
         fi
      done

      tagCat+="<Categories>"

      for item in ${!array[@]}; do
         tagCat+="<Category Assigned=\"1\">$item"

         for index in ${array["$item"]}; do
            tagCat+="<Category Assigned=\"1\">$index</Category>"
         done
         tagCat+="</Category>"
      done

      tagCat+="</Categories>"

      exiftool -overwrite_original_in_place -Categories="$tagCat" "$A"

      keyw=${keyw//;/,}
      keyw=${keyw%,*}

      tags=${tags// /,}
      tags=${tags//@/\/}

      echo "TAG : $tags"
      echo "KEY : $keyw"

      if [[ $tags != "" ]]; then
         exiftool -overwrite_original -sep "," -TagsList="$tags" -XMP-microsoft:LastKeywordXMP="$tags" "$A"

         tags=${tags//\//\|}
         exiftool -overwrite_original -sep "," -HierarchicalSubject="$tags" -XMP-mediapro:CatalogSets="$tags" "$A"

         exiftool -overwrite_original -sep "," -XPKeywords="$keyw" -Subject="$keyw" -Keywords="$keyw" -LastKeywordIPTC="$keyw" "$A"
      else
         printf "NO TAGS!! $A\n"
      fi
   fi
   tagCat=""
done
