#!/bin/bash
source Common.sh
for A in $FILES; do
   pre
   # 0 = 90CounterCLockwise and Vertical Flip (default)
   # 1 = 90Clockwise
   # 2 = 90CounterClockwise
   # 3 = 90Clockwise and Vertical Flip
   # transpose=2,transpose=2 = 180 degrees
   #    ffmpeg -hide_banner -loglevel panic -stats \
      # -y -i "$A" -threads 2 -b:v 15000k -vf "transpose=2" "${BASE}-rotated-${MYDATE}.mp4"
   NEWFILE="${BASEDIR}/${FILE_NO_EXT}-rotated-${MYDATE}.mp4"
   convert_it_video "$A" -threads 2 -vf "transpose=2" $NEWFILE
done
