#!/bin/bash
source Common.sh
for A in $FILES; do
    pre
    # 2 = 90CounterClockwise
    NEWFILE="${BASEDIR}/${FILE_NO_EXT}-rot-l-${MYDATE}.mp4"
    convert_it_video "$A" -threads 2 -vf "transpose=2" $NEWFILE
done
