#!/bin/bash

source Common.sh

for A in $FILES; do
   pre
   NEWFILE_1="${BASEDIR}/${FILE_NO_EXT}-1.mp4"
   NEWFILE_FINAL="${BASEDIR}/${FILE_NO_EXT}-filter.mp4"
   echo
   echo "Pass 1 ..."
   echo
   ffmpeg -i "$A" -vf "select='lt(scene,0.05)',setpts=N/FRAME_RATE/TB" \
          -vsync vfr "$NEWFILE_1"
   echo
   echo "Pass 2 ..."
   echo
   ffmpeg -i "$NEWFILE_1" -vf "select='lt(scene,0.05)',setpts=N/FRAME_RATE/TB" \
          -vsync vfr "$NEWFILE_FINAL"

   # tidy up
   rm -f "$NEWFILE_1"
done
