#!/bin/bash
source Common.sh

for A in $FILES; do
   pre
   NEWFILE="${BASEDIR}/${FILE_NO_EXT}-newaudio.mp4"
   convert_it_video "$A" \
                    -i "$BASEDIR/newaudio.wav" -c:v copy -map 0:v:0 -map 1:a:0 $NEWFILE
done
