#!/bin/bash
source Common.sh
for A in $FILES; do
   pre
   # slow down video and audio (video needs to have an audio)
   #    ffmpeg -hide_banner -loglevel panic -stats \
      # -y -i "$A" -threads 2 -filter_complex "[0:v]setpts=2*PTS[v];[0:a]atempo=0.5[a]" -map "[v]" -map "[a]" -r 30 "${BASE}-slow-${MYDATE}.mp4"

   NEWFILE="${BASEDIR}/${FILE_NO_EXT}-slow-${MYDATE}.mp4"
   convert_it_video "$A" -threads 2 -an -filter:v "setpts=5*PTS" -r 30 $NEWFILE
done
